### ISSUE TITLE
onMouseDown on component unmount

### ISSUE THREAD

**Issue by artaommahe** [mgechev/react-reorderable#9] opened 2015-09-07 22:39 UTC
If dragable components are unmount, onMouseDown event(if i get it right) continues to fires.

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.

**Comment by mgechev** [comment] 2015-09-08 05:58
Thanks! The issue is fixed now.

**Closed as completed** 2015-09-08 05:57 UTC
